-- Migration number: 0001 	 2025-03-26T21:11:49.543Z
CREATE TABLE Ballad (
	id TEXT PRIMARY KEY NOT NULL,
	title TEXT NOT NULL,
	ordinal INTEGER NOT NULL UNIQUE,
	link TEXT NOT NULL,
	prevId TEXT,
	nextId TEXT,
	FOREIGN KEY (prevId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY (nextId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Content (
	balladId TEXT NOT NULL,
	ordinal INTEGER NOT NULL,
	speaker TEXT,
	body TEXT NOT NULL,
	PRIMARY KEY(balladId, ordinal),
	FOREIGN KEY (balladId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Note (
	balladId INTEGER NOT NULL,
	ordinal INTEGER NOT NULL,
	body TEXT NOT NULL,
	PRIMARY KEY(balladId, ordinal),
	FOREIGN KEY (balladId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Motto (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	balladId TEXT NOT NULL,
	body TEXT NOT NULL,
	author TEXT NOT NULL,
	translation TEXT,
	FOREIGN KEY (balladId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Annotation (
	balladId TEXT NOT NULL,
	id INTEGER NOT NULL,
	body TEXT NOT NULL,
	PRIMARY KEY(balladId, id),
	FOREIGN KEY (balladId) REFERENCES Ballad(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

